---
- hosts: kubecluster
  become: true

  vars:
    docker_install_compose: false
    docker_users:
      - "{{ ansible_user }}"

    # Swap configuration.
    # swap_file_state: absent
    # swap_file_path: /dev/mapper/packer--debian--10--amd64--vg-swap_1

    # Kubernetes configuration.
    kubernetes_version: '1.16'
    kubernetes_allow_pods_on_master: false
    kubernetes_apiserver_advertise_address: '10.118.138.101'
    kubernetes_kubelet_extra_args: '--node-ip={{ ansible_host }}'

  pre_tasks:
    - name: install gpg on all nodes
      apt:
        name: gpg
        state: present

  roles:
    # - geerlingguy.security
    # - geerlingguy.swap
    # - geerlingguy.docker
    - geerlingguy.kubernetes
    # - myk8s
